#include "FX80Font.h"

#define _________ 0x0000
#define X________ 0x0001
#define _X_______ 0x0002
#define XX_______ 0x0003
#define __X______ 0x0004
#define X_X______ 0x0005
#define _XX______ 0x0006
#define XXX______ 0x0007
#define ___X_____ 0x0008
#define X__X_____ 0x0009
#define _X_X_____ 0x000a
#define XX_X_____ 0x000b
#define __XX_____ 0x000c
#define X_XX_____ 0x000d
#define _XXX_____ 0x000e
#define XXXX_____ 0x000f
#define ____X____ 0x0010
#define X___X____ 0x0011
#define _X__X____ 0x0012
#define XX__X____ 0x0013
#define __X_X____ 0x0014
#define X_X_X____ 0x0015
#define _XX_X____ 0x0016
#define XXX_X____ 0x0017
#define ___XX____ 0x0018
#define X__XX____ 0x0019
#define _X_XX____ 0x001a
#define XX_XX____ 0x001b
#define __XXX____ 0x001c
#define X_XXX____ 0x001d
#define _XXXX____ 0x001e
#define XXXXX____ 0x001f
#define _____X___ 0x0020
#define X____X___ 0x0021
#define _X___X___ 0x0022
#define XX___X___ 0x0023
#define __X__X___ 0x0024
#define X_X__X___ 0x0025
#define _XX__X___ 0x0026
#define XXX__X___ 0x0027
#define ___X_X___ 0x0028
#define X__X_X___ 0x0029
#define _X_X_X___ 0x002a
#define XX_X_X___ 0x002b
#define __XX_X___ 0x002c
#define X_XX_X___ 0x002d
#define _XXX_X___ 0x002e
#define XXXX_X___ 0x002f
#define ____XX___ 0x0030
#define X___XX___ 0x0031
#define _X__XX___ 0x0032
#define XX__XX___ 0x0033
#define __X_XX___ 0x0034
#define X_X_XX___ 0x0035
#define _XX_XX___ 0x0036
#define XXX_XX___ 0x0037
#define ___XXX___ 0x0038
#define X__XXX___ 0x0039
#define _X_XXX___ 0x003a
#define XX_XXX___ 0x003b
#define __XXXX___ 0x003c
#define X_XXXX___ 0x003d
#define _XXXXX___ 0x003e
#define XXXXXX___ 0x003f
#define ______X__ 0x0040
#define X_____X__ 0x0041
#define _X____X__ 0x0042
#define XX____X__ 0x0043
#define __X___X__ 0x0044
#define X_X___X__ 0x0045
#define _XX___X__ 0x0046
#define XXX___X__ 0x0047
#define ___X__X__ 0x0048
#define X__X__X__ 0x0049
#define _X_X__X__ 0x004a
#define XX_X__X__ 0x004b
#define __XX__X__ 0x004c
#define X_XX__X__ 0x004d
#define _XXX__X__ 0x004e
#define XXXX__X__ 0x004f
#define ____X_X__ 0x0050
#define X___X_X__ 0x0051
#define _X__X_X__ 0x0052
#define XX__X_X__ 0x0053
#define __X_X_X__ 0x0054
#define X_X_X_X__ 0x0055
#define _XX_X_X__ 0x0056
#define XXX_X_X__ 0x0057
#define ___XX_X__ 0x0058
#define X__XX_X__ 0x0059
#define _X_XX_X__ 0x005a
#define XX_XX_X__ 0x005b
#define __XXX_X__ 0x005c
#define X_XXX_X__ 0x005d
#define _XXXX_X__ 0x005e
#define XXXXX_X__ 0x005f
#define _____XX__ 0x0060
#define X____XX__ 0x0061
#define _X___XX__ 0x0062
#define XX___XX__ 0x0063
#define __X__XX__ 0x0064
#define X_X__XX__ 0x0065
#define _XX__XX__ 0x0066
#define XXX__XX__ 0x0067
#define ___X_XX__ 0x0068
#define X__X_XX__ 0x0069
#define _X_X_XX__ 0x006a
#define XX_X_XX__ 0x006b
#define __XX_XX__ 0x006c
#define X_XX_XX__ 0x006d
#define _XXX_XX__ 0x006e
#define XXXX_XX__ 0x006f
#define ____XXX__ 0x0070
#define X___XXX__ 0x0071
#define _X__XXX__ 0x0072
#define XX__XXX__ 0x0073
#define __X_XXX__ 0x0074
#define X_X_XXX__ 0x0075
#define _XX_XXX__ 0x0076
#define XXX_XXX__ 0x0077
#define ___XXXX__ 0x0078
#define X__XXXX__ 0x0079
#define _X_XXXX__ 0x007a
#define XX_XXXX__ 0x007b
#define __XXXXX__ 0x007c
#define X_XXXXX__ 0x007d
#define _XXXXXX__ 0x007e
#define XXXXXXX__ 0x007f
#define _______X_ 0x0080
#define X______X_ 0x0081
#define _X_____X_ 0x0082
#define XX_____X_ 0x0083
#define __X____X_ 0x0084
#define X_X____X_ 0x0085
#define _XX____X_ 0x0086
#define XXX____X_ 0x0087
#define ___X___X_ 0x0088
#define X__X___X_ 0x0089
#define _X_X___X_ 0x008a
#define XX_X___X_ 0x008b
#define __XX___X_ 0x008c
#define X_XX___X_ 0x008d
#define _XXX___X_ 0x008e
#define XXXX___X_ 0x008f
#define ____X__X_ 0x0090
#define X___X__X_ 0x0091
#define _X__X__X_ 0x0092
#define XX__X__X_ 0x0093
#define __X_X__X_ 0x0094
#define X_X_X__X_ 0x0095
#define _XX_X__X_ 0x0096
#define XXX_X__X_ 0x0097
#define ___XX__X_ 0x0098
#define X__XX__X_ 0x0099
#define _X_XX__X_ 0x009a
#define XX_XX__X_ 0x009b
#define __XXX__X_ 0x009c
#define X_XXX__X_ 0x009d
#define _XXXX__X_ 0x009e
#define XXXXX__X_ 0x009f
#define _____X_X_ 0x00a0
#define X____X_X_ 0x00a1
#define _X___X_X_ 0x00a2
#define XX___X_X_ 0x00a3
#define __X__X_X_ 0x00a4
#define X_X__X_X_ 0x00a5
#define _XX__X_X_ 0x00a6
#define XXX__X_X_ 0x00a7
#define ___X_X_X_ 0x00a8
#define X__X_X_X_ 0x00a9
#define _X_X_X_X_ 0x00aa
#define XX_X_X_X_ 0x00ab
#define __XX_X_X_ 0x00ac
#define X_XX_X_X_ 0x00ad
#define _XXX_X_X_ 0x00ae
#define XXXX_X_X_ 0x00af
#define ____XX_X_ 0x00b0
#define X___XX_X_ 0x00b1
#define _X__XX_X_ 0x00b2
#define XX__XX_X_ 0x00b3
#define __X_XX_X_ 0x00b4
#define X_X_XX_X_ 0x00b5
#define _XX_XX_X_ 0x00b6
#define XXX_XX_X_ 0x00b7
#define ___XXX_X_ 0x00b8
#define X__XXX_X_ 0x00b9
#define _X_XXX_X_ 0x00ba
#define XX_XXX_X_ 0x00bb
#define __XXXX_X_ 0x00bc
#define X_XXXX_X_ 0x00bd
#define _XXXXX_X_ 0x00be
#define XXXXXX_X_ 0x00bf
#define ______XX_ 0x00c0
#define X_____XX_ 0x00c1
#define _X____XX_ 0x00c2
#define XX____XX_ 0x00c3
#define __X___XX_ 0x00c4
#define X_X___XX_ 0x00c5
#define _XX___XX_ 0x00c6
#define XXX___XX_ 0x00c7
#define ___X__XX_ 0x00c8
#define X__X__XX_ 0x00c9
#define _X_X__XX_ 0x00ca
#define XX_X__XX_ 0x00cb
#define __XX__XX_ 0x00cc
#define X_XX__XX_ 0x00cd
#define _XXX__XX_ 0x00ce
#define XXXX__XX_ 0x00cf
#define ____X_XX_ 0x00d0
#define X___X_XX_ 0x00d1
#define _X__X_XX_ 0x00d2
#define XX__X_XX_ 0x00d3
#define __X_X_XX_ 0x00d4
#define X_X_X_XX_ 0x00d5
#define _XX_X_XX_ 0x00d6
#define XXX_X_XX_ 0x00d7
#define ___XX_XX_ 0x00d8
#define X__XX_XX_ 0x00d9
#define _X_XX_XX_ 0x00da
#define XX_XX_XX_ 0x00db
#define __XXX_XX_ 0x00dc
#define X_XXX_XX_ 0x00dd
#define _XXXX_XX_ 0x00de
#define XXXXX_XX_ 0x00df
#define _____XXX_ 0x00e0
#define X____XXX_ 0x00e1
#define _X___XXX_ 0x00e2
#define XX___XXX_ 0x00e3
#define __X__XXX_ 0x00e4
#define X_X__XXX_ 0x00e5
#define _XX__XXX_ 0x00e6
#define XXX__XXX_ 0x00e7
#define ___X_XXX_ 0x00e8
#define X__X_XXX_ 0x00e9
#define _X_X_XXX_ 0x00ea
#define XX_X_XXX_ 0x00eb
#define __XX_XXX_ 0x00ec
#define X_XX_XXX_ 0x00ed
#define _XXX_XXX_ 0x00ee
#define XXXX_XXX_ 0x00ef
#define ____XXXX_ 0x00f0
#define X___XXXX_ 0x00f1
#define _X__XXXX_ 0x00f2
#define XX__XXXX_ 0x00f3
#define __X_XXXX_ 0x00f4
#define X_X_XXXX_ 0x00f5
#define _XX_XXXX_ 0x00f6
#define XXX_XXXX_ 0x00f7
#define ___XXXXX_ 0x00f8
#define X__XXXXX_ 0x00f9
#define _X_XXXXX_ 0x00fa
#define XX_XXXXX_ 0x00fb
#define __XXXXXX_ 0x00fc
#define X_XXXXXX_ 0x00fd
#define _XXXXXXX_ 0x00fe
#define XXXXXXXX_ 0x00ff
#define ________X 0x0100
#define X_______X 0x0101
#define _X______X 0x0102
#define XX______X 0x0103
#define __X_____X 0x0104
#define X_X_____X 0x0105
#define _XX_____X 0x0106
#define XXX_____X 0x0107
#define ___X____X 0x0108
#define X__X____X 0x0109
#define _X_X____X 0x010a
#define XX_X____X 0x010b
#define __XX____X 0x010c
#define X_XX____X 0x010d
#define _XXX____X 0x010e
#define XXXX____X 0x010f
#define ____X___X 0x0110
#define X___X___X 0x0111
#define _X__X___X 0x0112
#define XX__X___X 0x0113
#define __X_X___X 0x0114
#define X_X_X___X 0x0115
#define _XX_X___X 0x0116
#define XXX_X___X 0x0117
#define ___XX___X 0x0118
#define X__XX___X 0x0119
#define _X_XX___X 0x011a
#define XX_XX___X 0x011b
#define __XXX___X 0x011c
#define X_XXX___X 0x011d
#define _XXXX___X 0x011e
#define XXXXX___X 0x011f
#define _____X__X 0x0120
#define X____X__X 0x0121
#define _X___X__X 0x0122
#define XX___X__X 0x0123
#define __X__X__X 0x0124
#define X_X__X__X 0x0125
#define _XX__X__X 0x0126
#define XXX__X__X 0x0127
#define ___X_X__X 0x0128
#define X__X_X__X 0x0129
#define _X_X_X__X 0x012a
#define XX_X_X__X 0x012b
#define __XX_X__X 0x012c
#define X_XX_X__X 0x012d
#define _XXX_X__X 0x012e
#define XXXX_X__X 0x012f
#define ____XX__X 0x0130
#define X___XX__X 0x0131
#define _X__XX__X 0x0132
#define XX__XX__X 0x0133
#define __X_XX__X 0x0134
#define X_X_XX__X 0x0135
#define _XX_XX__X 0x0136
#define XXX_XX__X 0x0137
#define ___XXX__X 0x0138
#define X__XXX__X 0x0139
#define _X_XXX__X 0x013a
#define XX_XXX__X 0x013b
#define __XXXX__X 0x013c
#define X_XXXX__X 0x013d
#define _XXXXX__X 0x013e
#define XXXXXX__X 0x013f
#define ______X_X 0x0140
#define X_____X_X 0x0141
#define _X____X_X 0x0142
#define XX____X_X 0x0143
#define __X___X_X 0x0144
#define X_X___X_X 0x0145
#define _XX___X_X 0x0146
#define XXX___X_X 0x0147
#define ___X__X_X 0x0148
#define X__X__X_X 0x0149
#define _X_X__X_X 0x014a
#define XX_X__X_X 0x014b
#define __XX__X_X 0x014c
#define X_XX__X_X 0x014d
#define _XXX__X_X 0x014e
#define XXXX__X_X 0x014f
#define ____X_X_X 0x0150
#define X___X_X_X 0x0151
#define _X__X_X_X 0x0152
#define XX__X_X_X 0x0153
#define __X_X_X_X 0x0154
#define X_X_X_X_X 0x0155
#define _XX_X_X_X 0x0156
#define XXX_X_X_X 0x0157
#define ___XX_X_X 0x0158
#define X__XX_X_X 0x0159
#define _X_XX_X_X 0x015a
#define XX_XX_X_X 0x015b
#define __XXX_X_X 0x015c
#define X_XXX_X_X 0x015d
#define _XXXX_X_X 0x015e
#define XXXXX_X_X 0x015f
#define _____XX_X 0x0160
#define X____XX_X 0x0161
#define _X___XX_X 0x0162
#define XX___XX_X 0x0163
#define __X__XX_X 0x0164
#define X_X__XX_X 0x0165
#define _XX__XX_X 0x0166
#define XXX__XX_X 0x0167
#define ___X_XX_X 0x0168
#define X__X_XX_X 0x0169
#define _X_X_XX_X 0x016a
#define XX_X_XX_X 0x016b
#define __XX_XX_X 0x016c
#define X_XX_XX_X 0x016d
#define _XXX_XX_X 0x016e
#define XXXX_XX_X 0x016f
#define ____XXX_X 0x0170
#define X___XXX_X 0x0171
#define _X__XXX_X 0x0172
#define XX__XXX_X 0x0173
#define __X_XXX_X 0x0174
#define X_X_XXX_X 0x0175
#define _XX_XXX_X 0x0176
#define XXX_XXX_X 0x0177
#define ___XXXX_X 0x0178
#define X__XXXX_X 0x0179
#define _X_XXXX_X 0x017a
#define XX_XXXX_X 0x017b
#define __XXXXX_X 0x017c
#define X_XXXXX_X 0x017d
#define _XXXXXX_X 0x017e
#define XXXXXXX_X 0x017f
#define _______XX 0x0180
#define X______XX 0x0181
#define _X_____XX 0x0182
#define XX_____XX 0x0183
#define __X____XX 0x0184
#define X_X____XX 0x0185
#define _XX____XX 0x0186
#define XXX____XX 0x0187
#define ___X___XX 0x0188
#define X__X___XX 0x0189
#define _X_X___XX 0x018a
#define XX_X___XX 0x018b
#define __XX___XX 0x018c
#define X_XX___XX 0x018d
#define _XXX___XX 0x018e
#define XXXX___XX 0x018f
#define ____X__XX 0x0190
#define X___X__XX 0x0191
#define _X__X__XX 0x0192
#define XX__X__XX 0x0193
#define __X_X__XX 0x0194
#define X_X_X__XX 0x0195
#define _XX_X__XX 0x0196
#define XXX_X__XX 0x0197
#define ___XX__XX 0x0198
#define X__XX__XX 0x0199
#define _X_XX__XX 0x019a
#define XX_XX__XX 0x019b
#define __XXX__XX 0x019c
#define X_XXX__XX 0x019d
#define _XXXX__XX 0x019e
#define XXXXX__XX 0x019f
#define _____X_XX 0x01a0
#define X____X_XX 0x01a1
#define _X___X_XX 0x01a2
#define XX___X_XX 0x01a3
#define __X__X_XX 0x01a4
#define X_X__X_XX 0x01a5
#define _XX__X_XX 0x01a6
#define XXX__X_XX 0x01a7
#define ___X_X_XX 0x01a8
#define X__X_X_XX 0x01a9
#define _X_X_X_XX 0x01aa
#define XX_X_X_XX 0x01ab
#define __XX_X_XX 0x01ac
#define X_XX_X_XX 0x01ad
#define _XXX_X_XX 0x01ae
#define XXXX_X_XX 0x01af
#define ____XX_XX 0x01b0
#define X___XX_XX 0x01b1
#define _X__XX_XX 0x01b2
#define XX__XX_XX 0x01b3
#define __X_XX_XX 0x01b4
#define X_X_XX_XX 0x01b5
#define _XX_XX_XX 0x01b6
#define XXX_XX_XX 0x01b7
#define ___XXX_XX 0x01b8
#define X__XXX_XX 0x01b9
#define _X_XXX_XX 0x01ba
#define XX_XXX_XX 0x01bb
#define __XXXX_XX 0x01bc
#define X_XXXX_XX 0x01bd
#define _XXXXX_XX 0x01be
#define XXXXXX_XX 0x01bf
#define ______XXX 0x01c0
#define X_____XXX 0x01c1
#define _X____XXX 0x01c2
#define XX____XXX 0x01c3
#define __X___XXX 0x01c4
#define X_X___XXX 0x01c5
#define _XX___XXX 0x01c6
#define XXX___XXX 0x01c7
#define ___X__XXX 0x01c8
#define X__X__XXX 0x01c9
#define _X_X__XXX 0x01ca
#define XX_X__XXX 0x01cb
#define __XX__XXX 0x01cc
#define X_XX__XXX 0x01cd
#define _XXX__XXX 0x01ce
#define XXXX__XXX 0x01cf
#define ____X_XXX 0x01d0
#define X___X_XXX 0x01d1
#define _X__X_XXX 0x01d2
#define XX__X_XXX 0x01d3
#define __X_X_XXX 0x01d4
#define X_X_X_XXX 0x01d5
#define _XX_X_XXX 0x01d6
#define XXX_X_XXX 0x01d7
#define ___XX_XXX 0x01d8
#define X__XX_XXX 0x01d9
#define _X_XX_XXX 0x01da
#define XX_XX_XXX 0x01db
#define __XXX_XXX 0x01dc
#define X_XXX_XXX 0x01dd
#define _XXXX_XXX 0x01de
#define XXXXX_XXX 0x01df
#define _____XXXX 0x01e0
#define X____XXXX 0x01e1
#define _X___XXXX 0x01e2
#define XX___XXXX 0x01e3
#define __X__XXXX 0x01e4
#define X_X__XXXX 0x01e5
#define _XX__XXXX 0x01e6
#define XXX__XXXX 0x01e7
#define ___X_XXXX 0x01e8
#define X__X_XXXX 0x01e9
#define _X_X_XXXX 0x01ea
#define XX_X_XXXX 0x01eb
#define __XX_XXXX 0x01ec
#define X_XX_XXXX 0x01ed
#define _XXX_XXXX 0x01ee
#define XXXX_XXXX 0x01ef
#define ____XXXXX 0x01f0
#define X___XXXXX 0x01f1
#define _X__XXXXX 0x01f2
#define XX__XXXXX 0x01f3
#define __X_XXXXX 0x01f4
#define X_X_XXXXX 0x01f5
#define _XX_XXXXX 0x01f6
#define XXX_XXXXX 0x01f7
#define ___XXXXXX 0x01f8
#define X__XXXXXX 0x01f9
#define _X_XXXXXX 0x01fa
#define XX_XXXXXX 0x01fb
#define __XXXXXXX 0x01fc
#define X_XXXXXXX 0x01fd
#define _XXXXXXXX 0x01fe
#define XXXXXXXXX 0x01ff

static struct glyph *Font[256];

#define GL(p,a,L1,L2,L3,L4,L5,L6,L7,L8,L9) { \
	a,{L1,L2,L3,L4,L5,L6,L7,L8,L9}}

// extracted from:
// https://minuszerodegrees.net/manuals/Epson%20FX-80%20Operation%20Manual.pdf

static struct glyph FontRom[] = {
	GL(0,224,
		___X_____,
		____X____,
		__X_X_X__,
		_______X_,
		_X_X_X_X_,
		X______X_,
		_X_X_X__X,
		_________,
		_________),
	GL(1,232,
		___X_____,
		____X____,
		_X_X_X_X_,
		X_______X,
		X_X_X_X_X,
		X________,
		_X_X_X_X_,
		_________,
		_________),
	GL(2,249,
		___X_____,
		____X____,
		_X_____X_,
		_X_____X_,
		_X_____X_,
		_X_____X_,
		___X_X__X,
		_________,
		_________),
	GL(3,242,
		___X_____,
		____X____,
		__X_X_X__,
		_X_____X_,
		_X_____X_,
		_X_____X_,
		__X_X_X__,
		_________,
		_________),
	GL(4,236,
		__X______,
		___X_____,
		_________,
		_X_X_____,
		___X_____,
		___X_____,
		_X_X_X___,
		_________,
		_________),
	GL(5,176,
		___X_X___,
		__X___X__,
		___X_X___,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________),
	GL(6,163,
		___X_X_X_,
		__X_____X,
		__X______,
		X_X_X____,
		__X______,
		__X______,
		X_X_X_X_X,
		_________,
		_________),
	GL(7,161,
		_________,
		____X____,
		_________,
		_________,
		____X____,
		____X____,
		____X____,
		____X____,
		_________),
	GL(8,191,
		_________,
		____X____,
		_________,
		____X____,
		__X______,
		X________,
		X_______X,
		__X_X_X__,
		_________),
	GL(9,209,
		_X_X____X,
		X____X_X_,
		_________,
		X_X_____X,
		X___X___X,
		X_____X_X,
		X_______X,
		_________,
		_________),
	GL(10,241,
		_X_X___X_,
		X___X_X__,
		_________,
		_X_X_X___,
		_X____X__,
		_X____X__,
		_X____X__,
		_________,
		_________),
	GL(11,164,
		X_______X,
		__X_X_X__,
		_X_____X_,
		X_______X,
		_X_____X_,
		__X_X_X__,
		X_______X,
		_________,
		_________),
	GL(12,0x20A7, // Pesetas
		X_X______,
		X___X____,
		X_X______,
		X_____X__,
		X___X_X_X,
		X_____X__,
		X_____X_X,
		_________,
		_________),
	GL(13,197,
		___X_X___,
		__X___X__,
		___X_X___,
		__X___X__,
		_X_____X_,
		X_X_X_X_X,
		X_______X,
		_________,
		_________),
	GL(14,229,
		____X____,
		_________,
		__X_X_X__,
		_______X_,
		_X_X_X_X_,
		X______X_,
		_X_X_X__X,
		_________,
		_________),
	GL(15,231,
		_________,
		_________,
		_X_X_X_X_,
		X________,
		X________,
		X________,
		_X_X_X_X_,
		_____X___,
		__X_X____),
	GL(16,167,
		__X_X_X__,
		_X_______,
		__X_X_X__,
		_X_____X_,
		__X_X_X__,
		_______X_,
		__X_X_X__,
		_________,
		_________),
	GL(17,223,
		_X_X_X___,
		X______X_,
		X______X_,
		X___X_X__,
		X______X_,
		X______X_,
		X___X_X__,
		_________,
		_________),
	GL(18,198,
		__X_X_X_X,
		_X__X____,
		X___X____,
		X_X_X_X_X,
		X___X____,
		X___X____,
		X___X_X_X,
		_________,
		_________),
	GL(19,230,
		_________,
		_________,
		X_X__X_X_,
		____X___X,
		X_X_X_X_X,
		X___X____,
		_X_X__X_X,
		_________,
		_________),
	GL(20,216,
		___X_X__X,
		_X_____X_,
		X____X__X,
		X___X___X,
		X__X____X,
		_X_____X_,
		X__X_X___,
		_________,
		_________),
	GL(21,248,
		_________,
		_________,
		___X_X__X,
		__X___X__,
		_X__X__X_,
		__X___X__,
		X__X_X___,
		_________,
		_________),
	GL(22,168,
		__X___X__,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________),
	GL(23,196,
		_X_____X_,
		____X____,
		___X_X___,
		__X___X__,
		_X_____X_,
		X_X_X_X_X,
		X_______X,
		_________,
		_________),
	GL(24,214,
		_X_____X_,
		_________,
		_X_X_X_X_,
		X_______X,
		X_______X,
		X_______X,
		_X_X_X_X_,
		_________,
		_________),
	GL(25,220,
		_X_____X_,
		_________,
		X_______X,
		X_______X,
		X_______X,
		X_______X,
		_X_X_X_X_,
		_________,
		_________),
	GL(26,228,
		__X___X__,
		_________,
		__X_X_X__,
		_______X_,
		_X_X_X_X_,
		X______X_,
		_X_X_X__X,
		_________,
		_________),
	GL(27,246,
		__X___X__,
		_________,
		__X_X_X__,
		_X_____X_,
		_X_____X_,
		_X_____X_,
		__X_X_X__,
		_________,
		_________),
	GL(28,252,
		__X___X__,
		_________,
		_X_____X_,
		_X_____X_,
		_X_____X_,
		_X_____X_,
		___X_X__X,
		_________,
		_________),
	GL(29,201,
		_____X___,
		____X____,
		X_X_X_X_X,
		X________,
		X_X_X_X__,
		X________,
		X_X_X_X_X,
		_________,
		_________),
	GL(30,233,
		_____X___,
		____X____,
		_X_X_X_X_,
		X_______X,
		X_X_X_X_X,
		X________,
		_X_X_X_X_,
		_________,
		_________),
	GL(31,165,
		X_______X,
		__X___X__,
		X_X_X_X_X,
		____X____,
		X_X_X_X_X,
		____X____,
		____X____,
		_________,
		_________),
     GL(32, ' ',
        _________,
        _________,
        _________,
        _________,
        _________,
        _________,
        _________,
        _________,
        _________),
     GL(33, '!',
        ____X____,
        ____X____,
        ____X____,
        ____X____,
        _________,
        _________,
        ____X____,
        _________,
        _________),
     GL(34, '"',
        __X___X__,
        __X___X__,
        __X___X__,
        _________,
        _________,
        _________,
        _________,
        _________,
        _________),
     GL(35, '#',
        __X___X__,
        __X___X__,
        X_X_X_X_X,
        __X___X__,
        X_X_X_X_X,
        __X___X__,
        __X___X__,
        _________,
        _________),
     GL(36, '$',
        ____X____,
        __X_X_X_X,
        X___X____,
        __X_X_X__,
        ____X___X,
        X_X_X_X__,
        ____X____,
        _________,
        _________),
     GL(37, '%',
        X_X____X_,
        X_X___X__,
        _____X___,
        ____X____,
        ___X_____,
        __X___X_X,
        _X____X_X,
        _________,
        _________),
     GL(38, '&',
        _X_X_____,
        X___X____,
        _X_X_____,
        __X_____X,
        X___X__X_,
        X_____X__,
        __X_X___X,
        _________,
        _________),
     GL(39, '\'',
        _____X___,
        ____X____,
        _________,
        _________,
        _________,
        _________,
        _________,
        _________,
        _________),
     GL(40, '(',
        ______X__,
        _____X___,
        ____X____,
        ____X____,
        ____X____,
        _____X___,
        ______X__,
        _________,
        _________),
     GL(41, ')',
        __X______,
        ___X_____,
        ____X____,
        ____X____,
        ____X____,
        ___X_____,
        __X______,
        _________,
        _________),
     GL(42, '*',
        _________,
        __X___X__,
        ___X_X___,
        X_X_X_X_X,
        ___X_X___,
        __X___X__,
        _________,
        _________,
        _________),
     GL(43, '+',
        _________,
        ____X____,
        ____X____,
        X_X_X_X_X,
        ____X____,
        ____X____,
        _________,
        _________,
        _________),
     GL(44, ',',
        _________,
        _________,
        _________,
        _________,
        _________,
        ___X_X___,
        ___X_X___,
        _____X___,
        ____X____),
     GL(45, '-',
        _________,
        _________,
        _________,
        X_X_X_X_X,
        _________,
        _________,
        _________,
        _________,
        _________),
     GL(46, '.',
        _________,
        _________,
        _________,
        _________,
        _________,
        __X_X____,
        __X_X____,
        _________,
        _________),
     GL(47, '/',
        _______X_,
        ______X__,
        _____X___,
        ____X____,
        ___X_____,
        __X______,
        _X_______,
        _________,
        _________),
     GL(48, '0',
        ___X_X___,
        _X_____X_,
        X_______X,
        X_______X,
        X_______X,
        _X_____X_,
        ___X_X___,
        _________,
        _________),
     GL(49, '1',
        ____X____,
        __X_X____,
        ____X____,
        ____X____,
        ____X____,
        ____X____,
        __X_X_X__,
        _________,
        _________),
     GL(50, '2',
        _X_X_X_X_,
        X_______X,
        ________X,
        ______X__,
        ____X____,
        __X______,
        X_X_X_X_X,
        _________,
        _________),
     GL(51, '3',
        X_X_X_X_X,
        ______X__,
        ____X____,
        ______X__,
        ________X,
        X_______X,
        __X_X_X__,
        _________,
        _________),
     GL(52, '4',
        ____X_X__,
        ___X__X__,
        __X___X__,
        _X____X__,
        X_X_X_X_X,
        ______X__,
        ______X__,
        _________,
        _________),
     GL(53, '5',
        X_X_X_X_X,
        X________,
        X_X_X_X__,
        ________X,
        ________X,
        X_______X,
        _X_X_X_X_,
        _________,
        _________),
     GL(54, '6',
        ____X____,
        ___X_____,
        __X______,
        _X_X_X_X_,
        X_______X,
        X_______X,
        _X_X_X_X_,
        _________,
        _________),
     GL(55, '7',
        X_X_X_X_X,
        _______X_,
        ______X__,
        _____X___,
        ____X____,
        ___X_____,
        __X______,
        _________,
        _________),
     GL(56, '8',
        __X_X_X__,
        _X_____X_,
        _X_____X_,
        __X_X_X__,
        X_______X,
        X_______X,
        _X_X_X_X_,
        _________,
        _________),
     GL(57, '9',
        _X_X_X_X_,
        X_______X,
        X_______X,
        _X_X_X_X_,
        ______X__,
        _____X___,
        ____X____,
        _________,
        _________),
     GL(58, ':',
        _________,
        _________,
        __X_X____,
        __X_X____,
        _________,		
        __X_X____,
        __X_X____,
        _________,
        _________),
     GL(59, ';',
        _________,
        _________,
        __X_X____,
        __X_X____,
        _________,
        __X_X____,
        __X_X____,
        ____X____,
        __X______),
     GL(60, '<',
        ______X__,
        ____X____,
        __X______,
        X________,
        __X______,
        ____X____,
        ______X__,
        _________,
        _________),
     GL(61, '=',
        _________,
        _________,
        X_X_X_X_X,
        _________,
        X_X_X_X_X,
        _________,
        _________,
        _________,
        _________),
     GL(62, '>',
        __X______,
        ____X____,
        ______X__,
        ________X,
        ______X__,
        ____X____,
        __X______,
        _________,
        _________),
     GL(63, '?',
        _X_X_X_X_,
        X_______X,
        ________X,
        ______X__,
        ____X____,
        _________,
        ____X____,
        _________,
        _________),
     GL(64, '@',
        __X_X_X__,
        _X______X,
        X___X_X_X,
        X__X____X,
        X___X_X_X,
        _X_______,
        __X_X_X_X,
        _________,
        _________),
     GL(65, 'A',
        ___X_X___,
        __X___X__,
        _X_____X_,
        X_______X,
        X_X_X_X_X,
        X_______X,
        X_______X,
        _________,
        _________),
     GL(66, 'B',
        X_X_X_X__,
        __X____X_,
        __X____X_,
        __X_X_X__,
        __X____X_,
        __X____X_,
        X_X_X_X__,
        _________,
        _________),
     GL(67, 'C',
        _X_X_X_X_,
        X_______X,
        X________,
        X________,
        X________,
        X_______X,
        _X_X_X_X_,
        _________,
        _________),
     GL(68, 'D',
        X_X_X_X__,
        __X____X_,
        __X_____X,
        __X_____X,
        __X_____X,
        __X____X_,
        X_X_X_X__,
        _________,
        _________),
     GL(69, 'E',
        X_X_X_X_X,
        X________,
        X________,
        X_X_X_X__,
        X________,
        X________,
        X_X_X_X_X,
        _________,
        _________),
     GL(70, 'F',
        X_X_X_X_X,
        X________,
        X________,
        X_X_X_X__,
        X________,
        X________,
        X________,
        _________,
        _________),
     GL(71, 'G',
        _X_X_X_X_,
        X_______X,
        X________,
        X___X_X_X,
        X_______X,
        X_______X,
        _X_X_X_X_,
        _________,
        _________),
     GL(72, 'H',
        X_______X,
        X_______X,
        X_______X,
        X_X_X_X_X,
        X_______X,
        X_______X,
        X_______X,
        _________,
        _________),
     GL(73, 'I',
        __X_X_X__,
        ____X____,
        ____X____,
        ____X____,
        ____X____,
        ____X____,
        __X_X_X__,
        _________,
        _________),
     GL(74, 'J',
        ___X_X_X_,
        ______X__,
        ______X__,
        ______X__,
        X_____X__,
        X_____X__,
        _X_X_X___,
        _________,
        _________),
     GL(75, 'K',
        X_______X,
        X_____X__,
        X___X____,
        X_X______,
        X___X____,
        X_____X__,
        X_______X,
        _________,
        _________),
     GL(76, 'L',
        X________,
        X________,
        X________,
        X________,
        X________,
        X________,
        X_X_X_X_X,
        _________,
        _________),
     GL(77, 'M',
        X_______X,
        X_X___X_X,
        X__X_X__X,
        X___X___X,
        X_______X,
        X_______X,
        X_______X,
        _________,
        _________),
     GL(78, 'N',
        X_______X,
        X_X_____X,
        X__X____X,
        X___X___X,
        X____X__X,
        X_____X_X,
        X_______X,
        _________,
        _________),
     GL(79, 'O',
        _X_X_X_X_,
        X_______X,
        X_______X,
        X_______X,
        X_______X,
        X_______X,
        _X_X_X_X_,
        _________,
        _________),
     GL(80, 'P',
        X_X_X_X__,
        X_______X,
        X_______X,
        X_X_X_X__,
        X________,
        X________,
        X________,
        _________,
        _________),
     GL(81, 'Q',
        _X_X_X_X_,
        X_______X,
        X_______X,
        X_______X,
        X___X___X,
        X_____X__,
        _X_X_X__X,
        _________,
        _________),
     GL(82, 'R',
        X_X_X_X__,
        X_______X,
        X_______X,
        X_X_X_X__,
        X_____X__,
        X______X_,
        X_______X,
        _________,
        _________),
     GL(83, 'S',
        _X_X_X_X_,
        X_______X,
        X________,
        _X_X_X_X_,
        ________X,
        X_______X,
        _X_X_X_X_,
        _________,
        _________),
     GL(84, 'T',
        X_X_X_X_X,
        ____X____,
        ____X____,
        ____X____,
        ____X____,
        ____X____,
        ____X____,
        _________,
        _________),
     GL(85, 'U',
        X_______X,
        X_______X,
        X_______X,
        X_______X,
        X_______X,
        X_______X,
        _X_X_X_X_,
        _________,
        _________),
     GL(86, 'V',
        X_______X,
        X_______X,
        X_______X,
        _X_____X_,
        __X___X__,
        ___X_X___,
        ____X____,
        _________,
        _________),
     GL(87, 'W',
        X_______X,
        X_______X,
        X___X___X,
        X___X___X,
        X__X_X__X,
        X_X___X_X,
        _X_____X_,
        _________,
        _________),
     GL(88, 'X',
        _X_____X_,
        __X___X__,
        ___X_X___,
        ____X____,
        ___X_X___,
        __X___X__,
        _X_____X_,
        _________,
        _________),
     GL(89, 'Y',
        X_______X,
        _X_____X_,
        __X___X__,
        ___X_X___,
        ____X____,
        ____X____,
        ____X____,
        _________,
        _________),
     GL(90, 'Z',
        _X_X_X_X_,
        ______X__,
        _____X___,
        ____X____,
        ___X_____,
        __X______,
        _X_X_X_X_,
        _________,
        _________),
     GL(91, '[',
        __X_X_X__,
        __X______,
        __X______,
        __X______,
        __X______,
        __X______,
        __X_X_X__,
        _________,
        _________),
     GL(92, '\\',
        _X_______,
        __X______,
        ___X_____,
        ____X____,
        _____X___,
        ______X__,
        _______X_,
        _________,
        _________),
     GL(93, ']',
        __X_X_X__,
        ______X__,
        ______X__,
        ______X__,
        ______X__,
        ______X__,
        __X_X_X__,
        _________,
        _________),
     GL(94, '^',
        ____X____,
        __X___X__,
        X_______X,
        _________,
        _________,
        _________,
        _________,
        _________,
        _________),
     GL(95, '_',
        _________,
        _________,
        _________,
        _________,
        _________,
        _________,
        _________,
        _________,
        _X_X_X_X_),
     GL(96, '`',
        ___X_____,
        ____X____,
        _________,
        _________,
        _________,
        _________,
        _________,
        _________,
        _________),
     GL(97, 'a',
        _________,
        _________,
        __X_X_X__,
        _______X_,
        _X_X_X_X_,
        X______X_,
        _X_X_X__X,
        _________,
        _________),
     GL(98, 'b',
        X________,
        X________,
        X_X_X_X__,
        X______X_,
        X______X_,
        X______X_,
        X_X_X_X__,
        _________,
        _________),
     GL(99, 'c',
        _________,
        _________,
        _X_X_X_X_,
        X________,
        X________,
        X________,
        _X_X_X_X_,
        _________,
        _________),
     GL(100, 'd',
        _______X_,
        _______X_,
        _X_X_X_X_,
        X______X_,
        X______X_,
        X______X_,
        _X_X_X_X_,
        _________,
        _________),
     GL(101, 'e',
        _________,
        _________,
        _X_X_X_X_,
        X_______X,
        X_X_X_X_X,
        X________,
        _X_X_X_X_,
        _________,
        _________),
     GL(102, 'f',
        ____X_X__,
        ___X_____,
        ___X_____,
        X_X_X_X__,
        ___X_____,
        ___X_____,
        ___X_____,
        _________,
        _________),
     GL(103, 'g',
        _________,
        _________,
        _X_X_X_X_,
        X______X_,
        X______X_,
        X______X_,
        _X_X_X_X_,
        _______X_,
        __X_X_X__),
     GL(104, 'h',
        X________,
        X________,
        X_X_X_X__,
        X______X_,
        X______X_,
        X______X_,
        X______X_,
        _________,
        _________),
     GL(105, 'i',
        ___X_____,
        _________,
        _X_X_____,
        ___X_____,
        ___X_____,
        ___X_____,
        _X_X_X___,
        _________,
        _________),
     GL(106, 'j',
        ______X__,
        _________,
        ____X_X__,
        ______X__,
        ______X__,
        ______X__,
        ______X__,
        _X_X_X___,
        _________),
     GL(107, 'k',
        _X_______,
        _X_______,
        _X_____X_,
        _X___X___,
        _X_X_____,
        _X___X___,
        _X_____X_,
        _________,
        _________),
     GL(108, 'l',
        _X_X_____,
        ___X_____,
        ___X_____,
        ___X_____,
        ___X_____,
        ___X_____,
        _X_X_X___,
        _________,
        _________),
     GL(109, 'm',
        _________,
        _________,
        _X_X_X_X_,
        X___X___X,
        X___X___X,
        X___X___X,
        X___X___X,
        _________,
        _________),
     GL(110, 'n',
        _________,
        _________,
        X_X_X_X__,
        X______X_,
        X______X_,
        X______X_,
        X______X_,
        _________,
        _________),
     GL(111, 'o',
        _________,
        _________,
        _X_X_X_X_,
        X_______X,
        X_______X,
        X_______X,
        _X_X_X_X_,
        _________,
        _________),
     GL(112, 'p',
        _________,
        _________,
        X_X_X_X__,
        X______X_,
        X______X_,
        X______X_,
        X_X_X_X__,
        X________,
        X________),
     GL(113, 'q',
        _________,
        _________,
        _X_X_X_X_,
        X______X_,
        X______X_,
        X______X_,
        _X_X_X_X_,
        _______X_,
        _______X_),
     GL(114, 'r',
        _________,
        _________,
        X__X_X_X_,
        X_X______,
        X________,
        X________,
        X________,
        _________,
        _________),
     GL(115, 's',
        _________,
        _________,
        _X_X_X_X_,
        X________,
        _X_X_X_X_,
        ________X,
        _X_X_X_X_,
        _________,
        _________),
     GL(116, 't',
        __X______,
        __X______,
        X_X_X_X__,
        __X______,
        __X______,
        __X______,
        ___X_X_X_,
        _________,
        _________),
     GL(117, 'u',
        _________,
        _________,
        X______X_,
        X______X_,
        X______X_,
        X______X_,
        _X_X_X__X,
        _________,
        _________),
     GL(118, 'v',
        _________,
        _________,
        X_______X,
        _X_____X_,
        __X___X__,
        ___X_X___,
        ____X____,
        _________,
        _________),
     GL(119, 'w',
        _________,
        _________,
        X_______X,
        X___X___X,
        X__X_X__X,
        X_X___X_X,
        _X_____X_,
        _________,
        _________),
     GL(120, 'x',
        _________,
        _________,
        X_____X__,
        _X___X___,
        ___X_____,
        _X___X___,
        X_____X__,
        _________,
        _________),
     GL(121, 'y',
        _________,
        _________,
        X_______X,
        _X_____X_,
        __X___X__,
        ___X_X___,
        ____X____,
        ___X_____,
        __X______),
     GL(122, 'z',
        _________,
        _________,
        X_X_X_X__,
        _____X___,
        ___X_____,
        _X_______,
        X_X_X_X__,
        _________,
        _________),
     GL(123, '{',
        _____X_X_,
        ____X____,
        ____X____,
        __X______,
        ____X____,
        ____X____,
        _____X_X_,
        _________,
        _________),
     GL(124, '|',
        ____X____,
        ____X____,
        ____X____,
        _________,
        ____X____,
        ____X____,
        ____X____,
        _________,
        _________),
     GL(125, '}',
        _X_X_____,
        ____X____,
        ____X____,
        ______X__,
        ____X____,
        ____X____,
        _X_X_____,
        _________,
        _________),
     GL(126, '~',
        _X_X_____,
        X___X___X,
        _____X_X_,
        _________,
        _________,
        _________,
        _________,
        _________,
        _________),
     GL(127, 127,
        _X_X_X_X_,
        X_____X_X,
        X____X__X,
        X___X___X,
        X__X____X,
        X_X_____X,
        _X_X_X_X_,
        _________,
        _________),
	GL(128,224,
		___X_____,
		____X____,
		__X_X_X__,
		_______X_,
		_X_X_X_X_,
		X_____X__,
		_X_X_X_X_,
		_________,
		_________),
	GL(129,232,
		___X_____,
		____X____,
		__X_X_X__,
		_X_____X_,
		X_X_X_X__,
		X________,
		_X_X_X___,
		_________,
		_________),
	GL(130,249,
		___X_____,
		____X____,
		_X_____X_,
		_X_____X_,
		X_____X__,
		X_____X__,
		_X_X_X_X_,
		_________,
		_________),
	GL(131,242,
		___X_____,
		____X____,
		___X__X__,
		_X_____X_,
		X______X_,
		X_____X__,
		_X__X____,
		_________,
		_________),
	GL(132,236,
		____X____,
		_____X___,
		_________,
		___X_X___,
		____X____,
		___X_____,
		_X_X_X___,
		_________,
		_________),
	GL(133,176,
		___X_X___,
		__X___X__,
		___X_X___,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________),
	GL(134,163,
		_____X_X_,
		___X____X,
		___X_____,
		X_X_X_X__,
		__X______,
		__X______,
		X_X_X_X__,
		_________,
		_________),
	GL(135,161,
		_______X_,
		_________,
		_________,
		_____X___,
		____X____,
		___X_____,
		__X______,
		_X_______,
		_________),
	GL(136,191,
		______X__,
		_________,
		_____X___,
		____X____,
		__X______,
		X________,
		X______X_,
		_X_X_X___,
		_________),
	GL(137,209,
		__X_X___X,
		_X___X_X_,
		_________,
		_X_____X_,
		_X_X___X_,
		X___X_X__,
		X_____X__,
		_________,
		_________),
	GL(138,241,
		__X_X___X,
		_X___X_X_,
		_________,
		X__X_X___,
		_X_____X_,
		_X_____X_,
		X_____X__,
		_________,
		_________),
	GL(139,164,
		___X____X,
		____X_X__,
		__X____X_,
		_X_____X_,
		_X____X__,
		__X_X____,
		X____X___,
		_________,
		_________),
	GL(140,0x20A7, // peseta ?
		__X_X_X__,
		__X___X__,
		_X_X_X___,
		_X____X__,
		_X__X_X_X,
		X____X___,
		X____X_X_,
		_________,
		_________),
	GL(141,197,
		_____X_X_,
		____X___X,
		_____X_X_,
		___X___X_,
		__X____X_,
		_X_X_X_X_,
		X______X_,
		_________,
		_________),
	GL(142,229,
		_____X___,
		_________,
		__X_X_X__,
		_______X_,
		_X_X_X_X_,
		X_____X__,
		_X_X_X_X_,
		_________,
		_________),
	GL(143,231,
		_________,
		_________,
		____X_X_X,
		__X______,
		_X_______,
		_X_______,
		___X_X_X_,
		_____X___,
		__X_X____),
	GL(144,167,
		____X_X_X,
		__X______,
		__X_X_X__,
		_X_____X_,
		__X_X_X__,
		______X__,
		X_X_X____,
		_________,
		_________),
	GL(145,223, // <-
		____X_X__,
		__X____X_,
		__X____X_,
		_X___X___,
		_X_____X_,
		X______X_,
		X___X_X__,
		_________,
		_________),
	GL(146,198,
		___X__X_X,
		__X__X___,
		_X___X___,
		_X_X_X_X_,
		X___X____,
		X___X____,
		X___X_X_X,
		_________,
		_________),
	GL(147,230,
		_________,
		_________,
		_X_X_X_X_,
		____X___X,
		__X_X_X__,
		X___X____,
		_X_X_X_X_,
		_________,
		_________),
	GL(148,216,
		____X_X_X,
		__X____X_,
		_X___X__X,
		X___X___X,
		X__X___X_,
		_X____X__,
		X_X_X____,
		_________,
		_________),
	GL(149,248,
		_________,
		______X__,
		___X_X___,
		_X__X__X_,
		X__X___X_,
		X__X__X__,
		__X_X____,
		_X_______,
		_________),
	GL(150,175,
		__X___X__,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________),
	GL(151,196,
		____X___X,
		_________,
		_____X_X_,
		___X___X_,
		__X____X_,
		_X_X_X_X_,
		X______X_,
		_________,
		_________),
	GL(152,214,
		___X___X_,
		_________,
		___X_X_X_,
		_X______X,
		X_______X,
		X______X_,
		_X_X_X___,
		_________,
		_________),
	GL(153,220,
		___X___X_,
		_________,
		_X______X,
		_X______X,
		X______X_,
		X______X_,
		_X_X_X___,
		_________,
		_________),
	GL(154,228,
		___X___X_,
		_________,
		__X_X_X__,
		_______X_,
		_X_X_X_X_,
		X_____X__,
		_X_X_X_X_,
		_________,
		_________),
	GL(155,246,
		___X___X_,
		_________,
		___X__X__,
		_X_____X_,
		X______X_,
		X_____X__,
		_X__X____,
		_________,
		_________),
	GL(156,252,
		__X____X_,
		_________,
		_X_____X_,
		_X_____X_,
		X_____X__,
		X_____X__,
		_X_X_X_X_,
		_________,
		_________),
	GL(157,201,
		_______X_,
		_____X___,
		__X_X_X_X,
		_X_______,
		_X_X_X___,
		X________,
		X_X_X_X__,
		_________,
		_________),
	GL(158,233,
		______X__,
		____X____,
		__X_X_X__,
		_X_____X_,
		X_X_X_X__,
		X________,
		_X_X_X___,
		_________,
		_________),
	GL(159,165,
		__X_____X,
		___X__X__,
		_X_X_X_X_,
		____X____,
		X_X_X_X__,
		___X_____,
		___X_____,
		_________,
		_________),
	 GL(160,32, // '
		_________,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________),
	GL(161,33,
		_______X_,
		______X__,
		_____X___,
		____X____,
		___X_____,
		_________,
		_X_______,
		_________,
		_________),
	GL(162,34,
		___X___X_,
		__X___X__,
		_X___X___,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________),
	GL(163,35,
		___X___X_,
		___X___X_,
		X_X_X_X_X,
		__X___X__,
		X_X_X_X_X,
		_X___X___,
		_X___X___,
		_________,
		_________),
	GL(164,36,
		_____X___,
		___X_X_X_,
		_X__X____,
		__X_X_X__,
		____X__X_,
		_X_X_X___,
		___X_____,
		_________,
		_________),
	GL(165,37,
		_X_X___X_,
		X_X___X__,
		_____X___,
		____X____,
		___X_____,
		__X___X_X,
		_X___X_X_,
		_________,
		_________),
	GL(166,38,
		___X_X___,
		__X___X__,
		___X_X___,
		_X__X___X,
		X____X_X_,
		X_____X__,
		__X_X__X_,
		_________,
		_________),
	GL(167,39,
		_____X___,
		____X____,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________),
	GL(168,40,
		_______X_,
		_____X___,
		____X____,
		___X_____,
		___X_____,
		___X_____,
		____X____,
		_________,
		_________),
	GL(169,41,
		____X____,
		_____X___,
		_____X___,
		_____X___,
		____X____,
		___X_____,
		_X_______,
		_________,
		_________),
	GL(170,42,
		_________,
		__X____X_,
		___X_X___,
		X_X_X_X_X,
		___X_X___,
		_X____X__,
		_________,
		_________,
		_________),
	GL(171,43,
		_________,
		______X__,
		_____X___,
		X_X_X_X_X,
		___X_____,
		__X______,
		_________,
		_________,
		_________),
	GL(172,44,
		_________,
		_________,
		_________,
		_________,
		_________,
		____X_X__,
		___X_X___,
		____X____,
		__X______),
	GL(173,45,
		_________,
		_________,
		_________,
		X_X_X_X_X,
		_________,
		_________,
		_________,
		_________,
		_________),
	GL(174,46,
		_________,
		_________,
		_________,
		_________,
		_________,
		___X_X___,
		__X_X____,
		_________,
		_________),
	GL(175,47,
		_______X_,
		______X__,
		_____X___,
		____X____,
		___X_____,
		__X______,
		_X_______,
		_________,
		_________),
	GL(176,48,
		____X_X__,
		__X_____X,
		_X______X,
		X_______X,
		X______X_,
		X_____X__,
		__X_X____,
		_________,
		_________),
	GL(177,49,
		______X__,
		___X_X___,
		_____X___,
		____X____,
		____X____,
		___X_____,
		_X_X_X___,
		_________,
		_________),
	GL(178,50,
		___X_X_X_,
		_X______X,
		________X,
		______X__,
		____X____,
		__X______,
		X_X_X_X__,
		_________,
		_________),
	GL(179,51,
		__X_X_X_X,
		_______X_,
		______X__,
		____X_X__,
		_______X_,
		X______X_,
		__X_X_X__,
		_________,
		_________),
	GL(180,52,
		_______X_,
		_____X_X_,
		___X__X__,
		_X____X__,
		X_X_X_X_X,
		_____X___,
		_____X___,
		_________,
		_________),
	GL(181,53,
		__X_X_X_X,
		_X_______,
		_X_X_X___,
		_______X_,
		_______X_,
		X_____X__,
		__X_X____,
		_________,
		_________),
	GL(182,54,
		______X__,
		____X____,
		__X______,
		_X_X_X___,
		X______X_,
		X______X_,
		__X_X_X__,
		_________,
		_________),
	GL(183,55,
		X_X_X_X_X,
		_______X_,
		_____X___,
		____X____,
		___X_____,
		__X______,
		_X_______,
		_________,
		_________),
	GL(184,56,
		___X_X_X_,
		_X______X,
		_X______X,
		__X_X_X__,
		X______X_,
		X______X_,
		_X_X_X___,
		_________,
		_________),
	GL(185,57,
		__X_X_X__,
		X______X_,
		X______X_,
		__X_X_X__,
		_____X___,
		___X_____,
		_X_______,
		_________,
		_________),
	GL(186,58,
		_________,
		_________,
		____X_X__,
		___X_X___,
		_________,
		___X_X___,
		__X_X____,
		_________,
		_________),
	GL(187,59,
		_________,
		_________,
		_____X_X_,
		____X_X__,
		_________,
		____X_X__,
		___X_X___,
		____X____,
		__X______),
	GL(188,60,
		_______X_,
		_____X___,
		___X_____,
		_X_______,
		__X______,
		___X_____,
		____X____,
		_________,
		_________),
	GL(189,61,
		_________,
		_________,
		_X_X_X_X_,
		_________,
		X_X_X_X__,
		_________,
		_________,
		_________,
		_________),
	GL(190,62,
		____X____,
		_____X___,
		______X__,
		_______X_,
		_____X___,
		___X_____,
		_X_______,
		_________,
		_________),
	GL(191,63,
		__X_X_X__,
		X______X_,
		_______X_,
		_____X___,
		___X_____,
		_________,
		_X_______,
		_________,
		_________),
	GL(192,64,
		___X_X_X_,
		__X_____X,
		_X____X_X,
		X___X___X,
		X____X_X_,
		X________,
		__X_X_X__,
		_________,
		_________),
	GL(193,65,
		______X_X,
		_____X__X,
		____X___X,
		___X____X,
		__X_X_X_X,
		_X______X,
		X_______X,
		_________,
		_________),
	GL(194,66,
		_X_X_X_X_,
		__X_____X,
		__X_____X,
		_X__X_X__,
		_X_____X_,
		X______X_,
		X_X_X_X__,
		_________,
		_________),
	GL(195,67,
		___X_X_X_,
		__X_____X,
		_X_______,
		X________,
		X________,
		X______X_,
		_X_X_X___,
		_________,
		_________),
	GL(196,68,
		_X_X_X_X_,
		__X_____X,
		__X_____X,
		_X______X,
		_X_____X_,
		X_____X__,
		X_X_X____,
		_________,
		_________),
	GL(197,69,
		__X_X_X_X,
		__X______,
		_X_______,
		_X_X_X___,
		_X_______,
		X________,
		X_X_X_X__,
		_________,
		_________),
	GL(198,70,
		__X_X_X_X,
		__X______,
		_X_______,
		_X_X_X___,
		_X_______,
		X________,
		X________,
		_________,
		_________),
	GL(199,71,
		___X_X_X_,
		__X_____X,
		_X_______,
		X____X_X_,
		X______X_,
		X_____X__,
		_X_X_X___,
		_________,
		_________),
	GL(200,72,
		__X_____X,
		__X_____X,
		_X_____X_,
		_X_X_X_X_,
		_X_____X_,
		X_____X__,
		X_____X__,
		_________,
		_________),
	GL(201,73,
		___X_X_X_,
		_____X___,
		_____X___,
		____X____,
		____X____,
		___X_____,
		_X_X_X___,
		_________,
		_________),
	GL(202,74,
		____X_X_X,
		_______X_,
		_______X_,
		______X__,
		X_____X__,
		X____X___,
		_X_X_____,
		_________,
		_________),
	GL(203,75,
		__X_____X,
		__X___X__,
		_X__X____,
		_X_X_____,
		_X___X___,
		X_____X__,
		X______X_,
		_________,
		_________),
	GL(204,76,
		____X____,
		___X_____,
		___X_____,
		__X______,
		__X______,
		_X_______,
		_X_X_X_X_,
		_________,
		_________),
	GL(205,77,
		__X_____X,
		__X___X_X,
		_X__X__X_,
		_X__X__X_,
		_X_____X_,
		X_____X__,
		X_____X__,
		_________,
		_________),
	GL(206,78,
		__X_____X,
		__X_____X,
		_X_X___X_,
		_X__X__X_,
		_X___X_X_,
		X_____X__,
		X_____X__,
		_________,
		_________),
	GL(207,79,
		___X_X_X_,
		__X_____X,
		_X______X,
		_X_____X_,
		X______X_,
		X_____X__,
		_X_X_X___,
		_________,
		_________),
	GL(208,80,
		___X_X_X_,
		__X_____X,
		__X_____X,
		_X_X_X_X_,
		_X_______,
		X________,
		X________,
		_________,
		_________),
	GL(209,81,
		____X_X__,
		__X_____X,
		_X______X,
		X_______X,
		X___X__X_,
		X_____X__,
		__X_X__X_,
		_________,
		_________),
	GL(210,82,
		___X_X_X_,
		__X_____X,
		__X_____X,
		_X__X_X__,
		_X___X___,
		X_____X__,
		X______X_,
		_________,
		_________),
	GL(211,83,
		___X_X_X_,
		_X______X,
		_X_______,
		___X_X___,
		_______X_,
		X______X_,
		_X_X_X___,
		_________,
		_________),
	GL(212,84,
		X_X_X_X_X,
		____X____,
		____X____,
		___X_____,
		___X_____,
		__X______,
		__X______,
		_________,
		_________),
	GL(213,85,
		__X_____X,
		__X_____X,
		_X_____X_,
		_X_____X_,
		X_____X__,
		X_____X__,
		_X_X_X___,
		_________,
		_________),
	GL(214,86,
		_X______X,
		_X_____X_,
		_X____X__,
		_X___X___,
		_X__X____,
		_X_X_____,
		_X_______,
		_________,
		_________),
	GL(215,87,
		__X_____X,
		__X_____X,
		_X_____X_,
		_X__X__X_,
		_X_X_X_X_,
		X_X___X__,
		X_____X__,
		_________,
		_________),
	GL(216,88,
		_X______X,
		__X____X_,
		___X_X___,
		____X____,
		__X_X____,
		_X___X___,
		X_____X__,
		_________,
		_________),
	GL(217,89,
		X_______X,
		_X_____X_,
		__X__X___,
		___X_____,
		___X_____,
		__X______,
		__X______,
		_________,
		_________),
	GL(218,90,
		__X_X_X_X,
		_______X_,
		______X__,
		____X____,
		__X______,
		_X_______,
		X_X_X_X__,
		_________,
		_________),
	GL(219,91,
		____X_X_X,
		___X_____,
		___X_____,
		__X______,
		__X______,
		_X_______,
		_X_X_X___,
		_________,
		_________),
	GL(220,92,
		__X______,
		__X______,
		___X_____,
		___X_____,
		____X____,
		____X____,
		_____X___,
		_________,
		_________),
	GL(221,93,
		___X_X_X_,
		______X__,
		______X__,
		_____X___,
		_____X___,
		____X____,
		X_X_X____,
		_________,
		_________),
	GL(222,94,
		_____X___,
		___X__X__,
		_X_____X_,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________),
	GL(223,95,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________,
		X_X_X_X_X),
	GL(224,96,
		___X_____,
		____X____,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________),
	GL(225,97,
		_________,
		_________,
		__X_X_X__,
		_______X_,
		_X_X_X_X_,
		X_____X__,
		_X_X_X_X_,
		_________,
		_________),
	GL(226,98,
		__X______,
		__X______,
		__X_X_X__,
		_X_____X_,
		_X_____X_,
		X_____X__,
		X_X_X____,
		_________,
		_________),
	GL(227,99,
		_________,
		_________,
		___X_X_X_,
		_X_______,
		X________,
		X________,
		__X_X_X__,
		_________,
		_________),
	GL(228,100,
		________X,
		________X,
		___X_X_X_,
		_X_____X_,
		X______X_,
		X_____X__,
		__X_X_X__,
		_________,
		_________),
	GL(229,101,
		_________,
		_________,
		__X_X_X__,
		_X_____X_,
		X_X_X_X__,
		X________,
		_X_X_X___,
		_________,
		_________),
	GL(230,102,
		______X_X,
		____X____,
		X_X_X_X__,
		___X_____,
		___X_____,
		__X______,
		__X______,
		_________,
		_________),
	GL(231,103,
		_________,
		_________,
		____X_X_X,
		__X_____X,
		_X_____X_,
		_X_____X_,
		__X_X_X__,
		______X__,
		__X_X____),
	GL(232,104,
		__X______,
		__X______,
		__X_X_X__,
		_X_____X_,
		_X_____X_,
		X_____X__,
		X_____X__,
		_________,
		_________),
	GL(233,105,
		______X__,
		_________,
		___X_X___,
		____X____,
		____X____,
		___X_____,
		_X_X_X___,
		_________,
		_________),
	GL(234,106,
		______X__,
		_________,
		____X_X__,
		_____X___,
		_____X___,
		____X____,
		____X____,
		X_X______,
		_________),
	GL(235,107,
		___X_____,
		__X______,
		__X____X_,
		_X___X___,
		_X_X_____,
		X___X____,
		X____X___,
		_________,
		_________),
	GL(236,108,
		____X_X__,
		_____X___,
		_____X___,
		____X____,
		____X____,
		___X_____,
		_X_X_X___,
		_________,
		_________),
	GL(237,109,
		_________,
		_________,
		X_X_X_X__,
		_X__X__X_,
		_X__X__X_,
		X__X__X__,
		X__X__X__,
		_________,
		_________),
	GL(238,110,
		_________,
		_________,
		X_X_X____,
		_X____X__,
		_X____X__,
		X____X___,
		X____X___,
		_________,
		_________),
	GL(239,111,
		_________,
		_________,
		___X__X__,
		_X_____X_,
		X______X_,
		X_____X__,
		_X__X____,
		_________,
		_________),
	GL(240,112,
		_________,
		_________,
		__X_X_X__,
		__X____X_,
		_X_____X_,
		_X____X__,
		_X_X_X___,
		X________,
		X________),
	GL(241,113,
		_________,
		_________,
		____X_X_X,
		__X_____X,
		_X_____X_,
		_X_____X_,
		__X_X_X__,
		______X__,
		______X__),
	GL(242,114,
		_________,
		_________,
		_X__X_X__,
		_X_X_____,
		_X_______,
		X________,
		X________,
		_________,
		_________),
	GL(243,115,
		_________,
		_________,
		___X_X_X_,
		_X_______,
		___X_X___,
		______X__,
		X_X_X____,
		_________,
		_________),
	GL(244,116,
		____X____,
		____X____,
		_X_X_X_X_,
		___X_____,
		__X______,
		__X______,
		___X_X___,
		_________,
		_________),
	GL(245,117,
		_________,
		_________,
		_X_____X_,
		_X_____X_,
		X_____X__,
		X_____X__,
		_X_X_X_X_,
		_________,
		_________),
	GL(246,118,
		_________,
		_________,
		_X_____X_,
		_X____X__,
		_X___X___,
		_X_X_____,
		_X_______,
		_________,
		_________),
	GL(247,119,
		_________,
		_________,
		_X______X,
		_X__X___X,
		X___X___X,
		X_X__X_X_,
		X______X_,
		_________,
		_________),
	GL(248,120,
		_________,
		_________,
		__X_____X,
		___X__X__,
		____X____,
		__X__X___,
		X_____X__,
		_________,
		_________),
	GL(249,121,
		_________,
		_________,
		_X______X,
		__X____X_,
		___X__X__,
		_____X___,
		____X____,
		___X_____,
		__X______),
	GL(250,122,
		_________,
		_________,
		__X_X_X_X,
		______X__,
		____X____,
		__X______,
		X_X_X_X__,
		_________,
		_________),
	GL(251,123,
		_____X_X_,
		____X____,
		____X____,
		_X_X_____,
		___X_____,
		__X______,
		___X_X___,
		_________,
		_________),
	GL(252,124,
		______X__,
		_____X___,
		____X____,
		_________,
		___X_____,
		__X______,
		_X_______,
		_________,
		_________),
	GL(253,125,
		___X_X___,
		______X__,
		_____X___,
		_____X_X_,
		____X____,
		____X____,
		_X_X_____,
		_________,
		_________),
	GL(254,126,
		_X_X_____,
		X___X___X,
		_____X_X_,
		_________,
		_________,
		_________,
		_________,
		_________,
		_________),
	GL(255,127,
		____X_X_X,
		__X____X_,
		_X___X__X,
		X___X___X,
		X__X___X_,
		_X____X__,
		X_X_X____,
		_________,
		_________)
};

static struct FontMap {
	unsigned char pos, glyph;
} 
cs_fr[] = {{64,0},{91,5},{92,15},{93,16},{123,30},{124,2},{125,1},{126,22}},
cs_de[] = {{64,16},{91,23},{92,24},{93,25},{123,26},{124,27},{125,28},{126,17}},
cs_uk[] = {{35,6}},
cs_dk[] = {{91,18},{92,20},{93,13},{123,19},{124,21},{125,14}},
cs_sw[] = {{36,11},{64,29},{91,23},{92,24},{93,13},{94,25},{96,30},{123,26},{124,27},{125,14},{126,28}},
cs_it[] = {{91,5},{93,30},{96,2},{123,0},{124,3},{125,1},{126,4}},
cs_sp[] = {{35,12},{91,7},{92,9},{93,8},{123,22},{124,10}},
cs_jp[] = {{92,31}};

static void FontDef(struct FontMap map[], int n) {
	for(int i=0; i<n; ++i) {
		int pos = map[i].pos, glyph = map[i].glyph;
		Font[pos+000] = &FontRom[glyph+000];
		Font[pos+128] = &FontRom[glyph+128];
	}
}

#define FD(x) FontDef(x,sizeof(x)/sizeof(x[0]))

struct glyph *FontGlyph(unsigned int charset, unsigned char ch) {
	static unsigned int last;
	
	if(last != charset || !Font[0]) {
		last = charset;
		for(int i=0; i<256; ++i) Font[i] = &FontRom[i];
		switch(charset) {
			case 1: FD(cs_fr); break;
			case 2: FD(cs_de); break;
			case 3: FD(cs_uk); break;
			case 4: FD(cs_dk); break;
			case 5: FD(cs_sw); break;
			case 6: FD(cs_it); break;
			case 7: FD(cs_sp); break;
			case 8: FD(cs_jp); break;
		}
	}
	return Font[ch];
}